name: Harvester

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: harvester

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
      working-directory: services/harvester
    - run: npm run build
      working-directory: services/harvester
    - uses: actions/cache@v2
      id: restore-build
      with:
        path: ./services/harvester/build
        key: ${{ github.sha }}

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    # Ensure build job passes before testing image.
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./services/harvester/build
          key: ${{ github.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run tests
        run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --file Dockerfile .
        working-directory: services/harvester

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./services/harvester/build
          key: ${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1 
        with:
          registry: registry.gitlab.com
          username: soulman-is-good
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Prepare tag
        run: |
          # IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=registry.gitlab.com/tradepump/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo "image_tag=$IMAGE_ID:$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/${{ env.IMAGE_NAME }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ env.image_tag }}
          push: true
